<span class="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold
    {{ match($status) {
        'CREATED' => 'bg-gray-100 text-gray-800',
        'AVAILABLE' => 'bg-blue-100 text-blue-800',
        'ACCEPTED' => 'bg-cyan-100 text-cyan-800',
        'PICKED_UP' => 'bg-indigo-100 text-indigo-800',
        'AT_DEPOT' => 'bg-yellow-100 text-yellow-800',
        'IN_TRANSIT' => 'bg-purple-100 text-purple-800',
        'OUT_FOR_DELIVERY' => 'bg-violet-100 text-violet-800',
        'DELIVERED' => 'bg-green-100 text-green-800',
        'DELIVERED_PAID' => 'bg-emerald-100 text-emerald-800',
        'PAID' => 'bg-emerald-100 text-emerald-800',
        'REFUSED' => 'bg-orange-100 text-orange-800',
        'RETURNED' => 'bg-red-100 text-red-800',
        'UNAVAILABLE' => 'bg-amber-100 text-amber-800',
        'VERIFIED' => 'bg-teal-100 text-teal-800',
        'CANCELLED' => 'bg-gray-100 text-gray-600',
        default => 'bg-gray-100 text-gray-800',
    } }}">
    {{ match($status) {
        'CREATED' => '🆕 Créé',
        'AVAILABLE' => '📋 Disponible',
        'ACCEPTED' => '✔️ Accepté',
        'PICKED_UP' => '🚚 Collecté',
        'AT_DEPOT' => '🏭 Au Dépôt',
        'IN_TRANSIT' => '🚛 En Transit',
        'OUT_FOR_DELIVERY' => '🚴 En Livraison',
        'DELIVERED' => '✅ Livré',
        'DELIVERED_PAID' => '💰 Livré & Payé',
        'PAID' => '💰 Payé',
        'REFUSED' => '🚫 Refusé',
        'RETURNED' => '↩️ Retourné',
        'UNAVAILABLE' => '⏸️ Indisponible',
        'VERIFIED' => '✔️ Vérifié',
        'CANCELLED' => '❌ Annulé',
        default => '📦 ' . $status,
    } }}
</span>
